CREATE SCHEMA VIDEO_CLUB DEFAULT CHARACTER SET utf8;

USE VIDEO_CLUB;

CREATE TABLE CLIENTE (
	Cedula CHAR(9) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR(20) NOT NULL,
	Telefono CHAR(8) NOT NULL,
	Correo VARCHAR(30),
	Direccion VARCHAR(100) NOT NULL,
	FechaRegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
	Id INT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(20) NOT NULL,
	Detalle VARCHAR(100) NOT NULL
);

CREATE TABLE VIDEOJUEGO (
	Codigo INT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Descripcion TEXT NOT NULL,
	Desarrollador VARCHAR(30) NOT NULL,
	FechaLanzamiento DATE NOT NULL,
	IdCategoria INT NOT NULL,
	CONSTRAINT VideojuegoCategoriaFK FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA(Id)
);

CREATE TABLE SUCURSAL (
	Numero INT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(30) NOT NULL
);

CREATE TABLE COPIA (
	Consecutivo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CodigoVideojuego INT NOT NULL,
	NumeroSucursal INT NOT NULL,
	FechaIngreso DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Disponibilidad CHAR NOT NULL DEFAULT 'S' CHECK (Disponibilidad IN ('S', 'N')),
	Estado VARCHAR(200),
	CONSTRAINT CopiaSucursalFK FOREIGN KEY (NumeroSucursal) REFERENCES SUCURSAL(Numero),
	CONSTRAINT CopiaVideojuegoFK FOREIGN KEY (CodigoVideojuego) REFERENCES VIDEOJUEGO(Codigo)
);

CREATE TABLE ALQUILER (
	Secuencia INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CedulaCliente CHAR(9) NOT NULL,
	ConsecutivoCopia INT NOT NULL,
	FechaPrestamo DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CantidadDias INT NOT NULL,
	FechaDevolucion DATETIME,
	DetalleDevolucion VARCHAR(200),
	CONSTRAINT AlquilerClienteFK FOREIGN KEY (CedulaCliente) REFERENCES CLIENTE(Cedula),
	CONSTRAINT AlquilerCopiaFK FOREIGN KEY (ConsecutivoCopia) REFERENCES COPIA(Consecutivo)
);

CREATE TABLE TRASLADO (
	NumeroOperacion INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ConsecutivoCopia INT NOT NULL,
	FechaTraslado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SucursalOrigen INT NOT NULL,
	SucursalDestino INT NOT NULL,
	Comentarios VARCHAR(100),
	CONSTRAINT TrasladoCopiaFK FOREIGN KEY (ConsecutivoCopia) REFERENCES COPIA(Consecutivo),
	CONSTRAINT TrasladoOrigenFK FOREIGN KEY (SucursalOrigen) REFERENCES SUCURSAL(Numero),
	CONSTRAINT TrasladoDestinoFK FOREIGN KEY (SucursalDestino) REFERENCES SUCURSAL(Numero)
);